services:
  pg:
    image: postgres:15.4-alpine
    restart: no
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - $PWD/.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: amd64/adminer:4.8.1
    restart: no
    depends_on:
      - pg
    ports:
      - 8083:8080
